### ISSUE TITLE
How to create multiple route files for different roles

### ISSUE THREAD

**Issue by itsursujit** [spiral/app#18]
Is there anyway I create multiple route files for different purpose?

For e.g.

api.php for RESTful routes
manager.php for Admin routes
web.php for Users routes

Also If above is possible, How would I add group middleware?

For e.g.
Group middleware to handle TOKEN for api.php
Group middleware to handle Admin role for manager.php
group middleware to handle all web related roles for web.php

**Comment by wolfy-j** [comment]
Have you checked route middleware?
