### ISSUE TITLE
What are the list of middlewares the framework provides?

### ISSUE THREAD

**Issue by itsursujit** [spiral/app#22]
When installing the framework what middleware we would get out-of-the box:

Preferred Categories
- Route Middleware
- Web Middleware
- Api Middleware
- Auth Middleware
- Cors Middleware
- CSRF Middleware

If they exists, then would be good to have some examples on how to use those.

**Comment by wolfy-j** [comment]
You have all of them, check the examples in HTTP section:

https://spiral.dev/docs/http-configuration

WebSockets located here https://spiral.dev/docs/broadcast-websockets
For cors see here - https://roadrunner.dev/docs/http-headers
For auth middleware - https://spiral.dev/docs/security-authentication#firewall-middleware
