### ISSUE TITLE
How to select columns in Repository

### ISSUE THREAD

**Issue by itsursujit** [spiral/app#25]
I want to hide some columns for some entities.

```
class UserRepository extends Repository implements ActorProviderInterface
{
    public function getActor(TokenInterface $token): ?object
    {
        if (!isset($token->getPayload()['userID'])) {
            return null;
        }

        return $this->findByPK($token->getPayload()['userID']);
    }
}
```

How would I hide the columns or add extra columns

**Comment by wolfy-j** [comment]
If you want to select partial models you have 2 options:
1) use Embeddings
2) use buildQuery of select and then call columns method, you will switch from ORM to DBAL
