### ISSUE TITLE
Cannot enable TCP_DEFER_ACCEPT: protocol not available

### ISSUE THREAD

**Issue by php-rock** [spiral/app#29]
/www/spiral/app $ ./spiral serve -v -d

DEBU[0000] [headers]: disabled
DEBU[0000] [grpc]: disabled
DEBU[0000] [amqp]: disabled
DEBU[0000] [beanstalk]: disabled
DEBU[0000] [sqs]: disabled
DEBU[0000] [ws]: disabled
DEBU[0000] [health]: disabled
DEBU[0000] [reload]: disabled
DEBU[0000] [rpc]: started
DEBU[0000] [http]: started
DEBU[0000] [jobs]: started
DEBU[0000] [broadcast]: started
DEBU[0000] [metrics]: started
ERRO[0000] [rpc]: [rpc]: cannot enable TCP_DEFER_ACCEPT: protocol not available
DEBU[0000] [http]: stopped
DEBU[0000] [jobs]: stopped
DEBU[0000] [broadcast]: stopped
DEBU[0000] [metrics]: stopped

Error: [rpc]: cannot enable TCP_DEFER_ACCEPT: protocol not available

**Comment by wolfy-j** [comment]
@php-rock what version of server do you use? Did you try to update and then run `vendor/bin/spiral get` ?

@48d90782

**Comment by 48d90782** [comment]
TCP_DEFER_ACCEPT Should work under all modern operating systems. @php-rock Could you please provide more info about:
1. Type of OS which you use. If that Ubuntu or other - `uname -r`, if Windows, if that WSL - same, `uname -r` inside it and also OS build version (could be found in settings section).
2. if that windows 7 or lower, we do not support operating systems lower that 18xxx builds of Win 10.
3. RR version.
FYI - TCP_DEFER_ACCEPT will work only in WSL2 (https://docs.microsoft.com/en-us/windows/wsl/install-win10). We generally do not support WSL, but WSL2 will work as a general server Linux os.
Thanks.

**Comment by rustatian** [comment]
We do not support WSL1, please update to WSL2 @php-rock
