### ISSUE TITLE
Version conflicts in skeleton

### ISSUE THREAD

**Issue by mark-ambrazhevich-spiral** [spiral/app#32]
In skeleton v1.1.3, there is  `"phpunit/phpunit": "^9.0" ` which requires php 7.3 which is conflict with  `"php": ">=7.2"` requirement. So it is impossible to create app fom skeleton in php 7.2.

**Comment by SerafimArts** [comment]
Yes, it's a skeleton bug.

To solve this problem now, use one of the command options below:
- `composer install --no-dev`
- `composer install --ignore-platform-reqs` (prefer)

**Comment by SerafimArts** [comment]
Done: https://github.com/spiral/app/releases/tag/v1.1.4
