### ISSUE TITLE
composer create-project spiral/app error

### ISSUE THREAD

**Issue by weirin** [spiral/app#36]
![image](https://user-images.githubusercontent.com/17962798/102852264-d79af680-4458-11eb-9d31-09e83881bf32.png)

**Comment by wolfy-j** [comment]
Do you have PHP-ZIP extension installed? If not - please download binary manually from releases page - https://github.com/spiral/roadrunner/releases

**Comment by weirin** [comment]
i see, thanks, good job wolfy, spiral is good.
