### ISSUE TITLE
PHP 8.1-php app.php encrypt:key -m .env doesn't work

### ISSUE THREAD

**Issue by jinrenjie** [spiral/app#46]
➜  PHP composer create-project spiral/app
Creating a "spiral/app" project at "./app"
Installing spiral/app (v1.4.0)
  - Downloading spiral/app (v1.4.0)
  - Installing spiral/app (v1.4.0): Extracting archive
Created project in /Users/George/Develop/PHP/app
Loading composer repositories with package information
Updating dependencies
Lock file operations: 95 installs, 0 updates, 0 removals
  - Locking cocur/slugify (v3.2)
  - Locking codedungeon/php-cli-colors (1.12.2)
  - Locking composer/package-versions-deprecated (1.11.99.4)
  - Locking cycle/annotated (v2.4.1)
  - Locking cycle/migrations (v1.0.10)
  - Locking cycle/orm (v1.8.0)
  - Locking cycle/proxy-factory (v1.3.1)
  - Locking cycle/schema-builder (v1.2.0)
  - Locking defuse/php-encryption (v2.3.1)
  - Locking doctrine/annotations (1.13.2)
  - Locking doctrine/collections (1.6.8)
  - Locking doctrine/inflector (2.0.4)
  - Locking doctrine/instantiator (1.4.0)
  - Locking doctrine/lexer (1.2.1)
  - Locking egulias/email-validator (3.1.2)
  - Locking laminas/laminas-diactoros (2.8.0)
  - Locking laminas/laminas-hydrator (4.3.1)
  - Locking laminas/laminas-stdlib (3.6.1)
  - Locking league/flysystem (2.3.2)
  - Locking league/mime-type-detection (1.9.0)
  - Locking monolog/monolog (2.3.5)
  - Locking myclabs/deep-copy (1.10.2)
  - Locking nikic/php-parser (v4.13.2)
  - Locking nyholm/psr7 (1.4.1)
  - Locking paragonie/random_compat (v9.99.100)
  - Locking phar-io/manifest (2.0.3)
  - Locking phar-io/version (3.1.0)
  - Locking php-http/message-factory (v1.0.2)
  - Locking phpdocumentor/reflection-common (2.2.0)
  - Locking phpdocumentor/reflection-docblock (5.3.0)
  - Locking phpdocumentor/type-resolver (1.5.1)
  - Locking phpoption/phpoption (1.8.1)
  - Locking phpspec/prophecy (1.14.0)
  - Locking phpunit/php-code-coverage (9.2.10)
  - Locking phpunit/php-file-iterator (3.0.6)
  - Locking phpunit/php-invoker (3.1.1)
  - Locking phpunit/php-text-template (2.0.4)
  - Locking phpunit/php-timer (5.0.3)
  - Locking phpunit/phpunit (9.5.10)
  - Locking psr/cache (3.0.0)
  - Locking psr/container (1.1.2)
  - Locking psr/event-dispatcher (1.0.0)
  - Locking psr/http-factory (1.0.1)
  - Locking psr/http-message (1.0.1)
  - Locking psr/http-server-handler (1.0.1)
  - Locking psr/http-server-middleware (1.0.1)
  - Locking psr/log (1.1.4)
  - Locking psr/simple-cache (3.0.0)
  - Locking sebastian/cli-parser (1.0.1)
  - Locking sebastian/code-unit (1.0.8)
  - Locking sebastian/code-unit-reverse-lookup (2.0.3)
  - Locking sebastian/comparator (4.0.6)
  - Locking sebastian/complexity (2.0.2)
  - Locking sebastian/diff (4.0.4)
  - Locking sebastian/environment (5.1.3)
  - Locking sebastian/exporter (4.0.4)
  - Locking sebastian/global-state (5.0.3)
  - Locking sebastian/lines-of-code (1.0.3)
  - Locking sebastian/object-enumerator (4.0.4)
  - Locking sebastian/object-reflector (2.0.4)
  - Locking sebastian/recursion-context (4.0.4)
  - Locking sebastian/resource-operations (3.0.3)
  - Locking sebastian/type (2.3.4)
  - Locking sebastian/version (3.0.2)
  - Locking spiral/composer-publish-plugin (v1.1.2)
  - Locking spiral/database (v2.9.3)
  - Locking spiral/framework (v2.8.13)
  - Locking spiral/goridge (v2.4.5)
  - Locking spiral/jobs (v2.2.2)
  - Locking spiral/migrations (v2.3.0)
  - Locking spiral/nyholm-bridge (v1.1.0)
  - Locking spiral/roadrunner (v1.9.2)
  - Locking symfony/console (v5.4.0)
  - Locking symfony/deprecation-contracts (v3.0.0)
  - Locking symfony/event-dispatcher (v6.0.0)
  - Locking symfony/event-dispatcher-contracts (v3.0.0)
  - Locking symfony/finder (v5.4.0)
  - Locking symfony/mailer (v5.4.0)
  - Locking symfony/mime (v6.0.0)
  - Locking symfony/polyfill-ctype (v1.23.0)
  - Locking symfony/polyfill-intl-grapheme (v1.23.1)
  - Locking symfony/polyfill-intl-idn (v1.23.0)
  - Locking symfony/polyfill-intl-normalizer (v1.23.0)
  - Locking symfony/polyfill-mbstring (v1.23.1)
  - Locking symfony/polyfill-php72 (v1.23.0)
  - Locking symfony/polyfill-php73 (v1.23.0)
  - Locking symfony/polyfill-php80 (v1.23.1)
  - Locking symfony/service-contracts (v2.4.1)
  - Locking symfony/string (v6.0.0)
  - Locking symfony/translation (v5.4.0)
  - Locking symfony/translation-contracts (v2.5.0)
  - Locking theseer/tokenizer (1.2.1)
  - Locking vlucas/phpdotenv (v3.6.9)
  - Locking webmozart/assert (1.10.0)
  - Locking yiisoft/friendly-exception (1.1.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 95 installs, 0 updates, 0 removals
  - Downloading spiral/composer-publish-plugin (v1.1.2)
  - Downloading composer/package-versions-deprecated (1.11.99.4)
  - Downloading cocur/slugify (v3.2)
  - Downloading codedungeon/php-cli-colors (1.12.2)
  - Downloading vlucas/phpdotenv (v3.6.9)
  - Downloading symfony/translation (v5.4.0)
  - Downloading symfony/mime (v6.0.0)
  - Downloading psr/log (1.1.4)
  - Downloading egulias/email-validator (3.1.2)
  - Downloading symfony/mailer (v5.4.0)
  - Downloading psr/simple-cache (3.0.0)
  - Downloading psr/http-server-handler (1.0.1)
  - Downloading psr/http-server-middleware (1.0.1)
  - Downloading psr/cache (3.0.0)
  - Downloading league/flysystem (2.3.2)
  - Downloading doctrine/annotations (1.13.2)
  - Downloading paragonie/random_compat (v9.99.100)
  - Downloading defuse/php-encryption (v2.3.1)
  - Downloading spiral/framework (v2.8.13)
  - Downloading yiisoft/friendly-exception (1.1.0)
  - Downloading spiral/database (v2.9.3)
  - Downloading laminas/laminas-stdlib (3.6.1)
  - Downloading laminas/laminas-hydrator (4.3.1)
  - Downloading doctrine/collections (1.6.8)
  - Downloading cycle/orm (v1.8.0)
  - Downloading cycle/schema-builder (v1.2.0)
  - Downloading cycle/annotated (v2.4.1)
  - Downloading spiral/migrations (v2.3.0)
  - Downloading cycle/migrations (v1.0.10)
  - Downloading cycle/proxy-factory (v1.3.1)
  - Downloading php-http/message-factory (v1.0.2)
  - Downloading phpunit/php-code-coverage (9.2.10)
  - Downloading spiral/goridge (v2.4.5)
  - Downloading spiral/roadrunner (v1.9.2)
  - Downloading spiral/jobs (v2.2.2)
  - Downloading nyholm/psr7 (1.4.1)
  - Downloading spiral/nyholm-bridge (v1.1.0)
  - Installing spiral/composer-publish-plugin (v1.1.2): Extracting archive
  - Installing composer/package-versions-deprecated (1.11.99.4): Extracting archive
  - Installing cocur/slugify (v3.2): Extracting archive
  - Installing codedungeon/php-cli-colors (1.12.2): Extracting archive
  - Installing symfony/polyfill-ctype (v1.23.0): Extracting archive
  - Installing phpoption/phpoption (1.8.1): Extracting archive
  - Installing vlucas/phpdotenv (v3.6.9): Extracting archive
  - Installing symfony/translation-contracts (v2.5.0): Extracting archive
  - Installing symfony/polyfill-php80 (v1.23.1): Extracting archive
  - Installing symfony/polyfill-mbstring (v1.23.1): Extracting archive
  - Installing symfony/deprecation-contracts (v3.0.0): Extracting archive
  - Installing symfony/translation (v5.4.0): Extracting archive
  - Installing symfony/polyfill-php73 (v1.23.0): Extracting archive
  - Installing psr/container (1.1.2): Extracting archive
  - Installing symfony/service-contracts (v2.4.1): Extracting archive
  - Installing symfony/polyfill-php72 (v1.23.0): Extracting archive
  - Installing symfony/polyfill-intl-normalizer (v1.23.0): Extracting archive
  - Installing symfony/polyfill-intl-idn (v1.23.0): Extracting archive
  - Installing symfony/mime (v6.0.0): Extracting archive
  - Installing psr/event-dispatcher (1.0.0): Extracting archive
  - Installing symfony/event-dispatcher-contracts (v3.0.0): Extracting archive
  - Installing symfony/event-dispatcher (v6.0.0): Extracting archive
  - Installing psr/log (1.1.4): Extracting archive
  - Installing doctrine/lexer (1.2.1): Extracting archive
  - Installing egulias/email-validator (3.1.2): Extracting archive
  - Installing symfony/mailer (v5.4.0): Extracting archive
  - Installing symfony/finder (v5.4.0): Extracting archive
  - Installing symfony/polyfill-intl-grapheme (v1.23.1): Extracting archive
  - Installing symfony/string (v6.0.0): Extracting archive
  - Installing symfony/console (v5.4.0): Extracting archive
  - Installing psr/simple-cache (3.0.0): Extracting archive
  - Installing psr/http-message (1.0.1): Extracting archive
  - Installing psr/http-server-handler (1.0.1): Extracting archive
  - Installing psr/http-server-middleware (1.0.1): Extracting archive
  - Installing psr/http-factory (1.0.1): Extracting archive
  - Installing psr/cache (3.0.0): Extracting archive
  - Installing nikic/php-parser (v4.13.2): Extracting archive
  - Installing myclabs/deep-copy (1.10.2): Extracting archive
  - Installing monolog/monolog (2.3.5): Extracting archive
  - Installing league/mime-type-detection (1.9.0): Extracting archive
  - Installing league/flysystem (2.3.2): Extracting archive
  - Installing doctrine/inflector (2.0.4): Extracting archive
  - Installing doctrine/annotations (1.13.2): Extracting archive
  - Installing paragonie/random_compat (v9.99.100): Extracting archive
  - Installing defuse/php-encryption (v2.3.1): Extracting archive
  - Installing spiral/framework (v2.8.13): Extracting archive
  - Installing yiisoft/friendly-exception (1.1.0): Extracting archive
  - Installing spiral/database (v2.9.3): Extracting archive
  - Installing webmozart/assert (1.10.0): Extracting archive
  - Installing laminas/laminas-stdlib (3.6.1): Extracting archive
  - Installing laminas/laminas-hydrator (4.3.1): Extracting archive
  - Installing doctrine/instantiator (1.4.0): Extracting archive
  - Installing doctrine/collections (1.6.8): Extracting archive
  - Installing cycle/orm (v1.8.0): Extracting archive
  - Installing cycle/schema-builder (v1.2.0): Extracting archive
  - Installing cycle/annotated (v2.4.1): Extracting archive
  - Installing spiral/migrations (v2.3.0): Extracting archive
  - Installing cycle/migrations (v1.0.10): Extracting archive
  - Installing cycle/proxy-factory (v1.3.1): Extracting archive
  - Installing php-http/message-factory (v1.0.2): Extracting archive
  - Installing phpdocumentor/reflection-common (2.2.0): Extracting archive
  - Installing phpdocumentor/type-resolver (1.5.1): Extracting archive
  - Installing phpdocumentor/reflection-docblock (5.3.0): Extracting archive
  - Installing sebastian/version (3.0.2): Extracting archive
  - Installing sebastian/type (2.3.4): Extracting archive
  - Installing sebastian/resource-operations (3.0.3): Extracting archive
  - Installing sebastian/recursion-context (4.0.4): Extracting archive
  - Installing sebastian/object-reflector (2.0.4): Extracting archive
  - Installing sebastian/object-enumerator (4.0.4): Extracting archive
  - Installing sebastian/global-state (5.0.3): Extracting archive
  - Installing sebastian/exporter (4.0.4): Extracting archive
  - Installing sebastian/environment (5.1.3): Extracting archive
  - Installing sebastian/diff (4.0.4): Extracting archive
  - Installing sebastian/comparator (4.0.6): Extracting archive
  - Installing sebastian/code-unit (1.0.8): Extracting archive
  - Installing sebastian/cli-parser (1.0.1): Extracting archive
  - Installing phpunit/php-timer (5.0.3): Extracting archive
  - Installing phpunit/php-text-template (2.0.4): Extracting archive
  - Installing phpunit/php-invoker (3.1.1): Extracting archive
  - Installing phpunit/php-file-iterator (3.0.6): Extracting archive
  - Installing theseer/tokenizer (1.2.1): Extracting archive
  - Installing sebastian/lines-of-code (1.0.3): Extracting archive
  - Installing sebastian/complexity (2.0.2): Extracting archive
  - Installing sebastian/code-unit-reverse-lookup (2.0.3): Extracting archive
  - Installing phpunit/php-code-coverage (9.2.10): Extracting archive
  - Installing phpspec/prophecy (1.14.0): Extracting archive
  - Installing phar-io/version (3.1.0): Extracting archive
  - Installing phar-io/manifest (2.0.3): Extracting archive
  - Installing phpunit/phpunit (9.5.10): Extracting archive
  - Installing spiral/goridge (v2.4.5): Extracting archive
  - Installing laminas/laminas-diactoros (2.8.0): Extracting archive
  - Installing spiral/roadrunner (v1.9.2): Extracting archive
  - Installing spiral/jobs (v2.2.2): Extracting archive
  - Installing nyholm/psr7 (1.4.1): Extracting archive
  - Installing spiral/nyholm-bridge (v1.1.0): Extracting archive
25 package suggestions were added by new dependencies, use `composer suggest` to see details.
Generating autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
58 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> php -r "copy('.env.sample', '.env');"
> php app.php encrypt:key -m .env
Fatal error: During inheritance of ArrayAccess: Uncaught ErrorException: Return type of Dotenv\Environment\AbstractVariables::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/George/Develop/PHP/app/vendor/vlucas/phpdotenv/src/Environment/AbstractVariables.php:162
Stack trace:
#0 /Users/George/Develop/PHP/app/vendor/vlucas/phpdotenv/src/Environment/AbstractVariables.php(13): Spiral\Boot\ExceptionHandler::handleError(8192, 'Return type of ...', '/Users/George/D...', 162)
#1 /Users/George/Develop/PHP/app/vendor/composer/ClassLoader.php(571): include('/Users/George/D...')
#2 /Users/George/Develop/PHP/app/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/Users/George/D...')
#3 /Users/George/Develop/PHP/app/vendor/vlucas/phpdotenv/src/Environment/DotenvVariables.php(8): Composer\Autoload\ClassLoader->loadClass('Dotenv\\Environm...')
#4 /Users/George/Develop/PHP/app/vendor/composer/ClassLoader.php(571): include('/Users/George/D...')
#5 /Users/George/Develop/PHP/app/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/Users/George/D...')
#6 /Users/George/Develop/PHP/app/vendor/vlucas/phpdotenv/src/Environment/DotenvFactory.php(56): Composer\Autoload\ClassLoader->loadClass('Dotenv\\Environm...')
#7 /Users/George/Develop/PHP/app/vendor/vlucas/phpdotenv/src/Loader.php(75): Dotenv\Environment\DotenvFactory->createImmutable()
#8 /Users/George/Develop/PHP/app/vendor/vlucas/phpdotenv/src/Loader.php(62): Dotenv\Loader->setImmutable(true)
#9 /Users/George/Develop/PHP/app/vendor/vlucas/phpdotenv/src/Dotenv.php(50): Dotenv\Loader->__construct(Array, Object(Dotenv\Environment\DotenvFactory), true)
#10 /Users/George/Develop/PHP/app/vendor/spiral/framework/src/Bridge/Dotenv/src/Bootloader/DotenvBootloader.php(36): Dotenv\Dotenv::create('/Users/George/D...', '.env')
#11 [internal function]: Spiral\DotEnv\Bootloader\DotenvBootloader->boot(Object(Spiral\Boot\Directories), Object(Spiral\Boot\Environment), Array)
#12 /Users/George/Develop/PHP/app/vendor/spiral/framework/src/Boot/src/BootloadManager.php(123): ReflectionMethod->invokeArgs(Object(Spiral\DotEnv\Bootloader\DotenvBootloader), Array)
#13 /Users/George/Develop/PHP/app/vendor/spiral/framework/src/Boot/src/BootloadManager.php(97): Spiral\Boot\BootloadManager->initBootloader(Object(Spiral\DotEnv\Bootloader\DotenvBootloader), Array)
#14 /Users/George/Develop/PHP/app/vendor/spiral/framework/src/Boot/src/BootloadManager.php(65): Spiral\Boot\BootloadManager->boot(Array)
#15 /Users/George/Develop/PHP/app/vendor/spiral/framework/src/Core/src/Container.php(268): Spiral\Boot\BootloadManager->Spiral\Boot\{closure}()
#16 /Users/George/Develop/PHP/app/vendor/spiral/framework/src/Boot/src/BootloadManager.php(66): Spiral\Core\Container->runScope(Array, Object(Closure))
#17 /Users/George/Develop/PHP/app/vendor/spiral/framework/src/Boot/src/AbstractKernel.php(172): Spiral\Boot\BootloadManager->bootload(Array)
#18 /Users/George/Develop/PHP/app/vendor/spiral/framework/src/Boot/src/AbstractKernel.php(141): Spiral\Boot\AbstractKernel->bootload()
#19 /Users/George/Develop/PHP/app/vendor/spiral/framework/src/Core/src/ContainerScope.php(50): Spiral\Boot\AbstractKernel::Spiral\Boot\{closure}()
#20 /Users/George/Develop/PHP/app/vendor/spiral/framework/src/Core/src/Container.php(265): Spiral\Core\ContainerScope::runScope(Object(Spiral\Core\Container), Object(Closure))
#21 /Users/George/Develop/PHP/app/vendor/spiral/framework/src/Boot/src/AbstractKernel.php(143): Spiral\Core\Container->runScope(Array, Object(Closure))
#22 /Users/George/Develop/PHP/app/app.php(33): Spiral\Boot\AbstractKernel::init(Array)
#23 {main} in /Users/George/Develop/PHP/app/vendor/vlucas/phpdotenv/src/Environment/AbstractVariables.php on line 13

**Comment by dmekhov** [comment]
It seems not actual with spiral/app (v2.0.0)
