### ISSUE TITLE
Could not install spiral framework on windows 10

### ISSUE THREAD

**Issue by olaseyo** [spiral/app#51]
### Description
I got the below error while trying to install on windows 10
Warning: ZipArchive::getStream(): Invalid or uninitialized Zip object in C:\Users\HP\Documents\Fro Mac\Project\Docspera\jolter_master\app\vendor\spiral\framework\bin\spiral on line 165

### How To Reproduce

run the command `composer create-project spiral/app`

### Additional Info

| Q                   | A
| ------------------- | ---
| Framework Version   | ^2.8 
| PHP version         | 7.4 
| Operating system    | Windows (10)

**Comment by olaseyo** [comment]
Thanks for that. I was able to download it now but still could not serve
Got the error below.
handle_serve_command: Init error:
        endure_initialize:
        endure_internal_init: Function call error:
        endure_call_init_fn:
        config_plugin_init: incompatible versions passed: from: 2.6.0, to: 2.8.0

**Comment by butschster** [comment]
Try to add `version: '2.7'` at the begining of `.rr.yaml`

**Comment by olaseyo** [comment]
Running this command 
`./rr.exe serve  rr.yaml `
Produce this output :
"[INFO] RoadRunner server started; version: 2.8.1, buildtime: 2022-02-21T08:02:19+0000"


After that i ran this command
`grpcui -plaintext -proto event.proto localhost:8150`
But got an error i have not been able to fix.


Output: 
"Failed to dial target host "localhost:8150": dial tcp [::1]:8150: connectex: No connection could be made because the target machine actively refused it."

**Comment by butschster** [comment]
https://github.com/spiral/app/pull/140
