### ISSUE TITLE
Undefined class or binding `Symfony\Contracts\HttpClient\HttpClientInterface` 

### ISSUE THREAD

**Issue by roquie** [spiral/app#67]
`[App\Job\Ping] Undefined class or binding "Symfony\Contracts\HttpClient\HttpClientInterface"` error happens when I click on "Create background task" on main page after first app skeleton start. I don't think this is expected behavior.

How to reproduce:
1. `composer create-project spiral/app backend v3.0-beta2`
2. `./rr serve`
3. Open http://localhost:8080
4. Click to "Create background task" link

**Comment by msmakouz** [comment]
Fixed by:
https://github.com/spiral/app/pull/74
