### ISSUE TITLE
Application router conflicts with `static` RR plugin

### ISSUE THREAD

**Issue by roquie** [spiral/app#68]
Looks like a bug but not a bug. I'm a little bit confused because `public` directory do not contains these "files". Why this happens?

<img width="1680" alt="Screenshot 2022-08-18 at 17 49 26" src="https://user-images.githubusercontent.com/3214290/185425044-6d4345d5-30d6-44b7-b9b3-a56477bdcd39.png">

Versions:
* PHP: `8.1.8`
* Skeleton: `v3.0-beta2`

**Comment by butschster** [comment]
Look like an expected behaviour RR with enabled `static` middleware and route with some file extension (`.html`, `.txt`, etc.)
